# Generated by Carter Pape's custom Ubuntu setup script

setopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS
setopt SHARE_HISTORY
setopt MAIL_WARNING

export EDITOR="nano"
export VISUAL="nano"

setprompt() {
    autoload -Uz vcs_info
    zstyle ':vcs_info:*' enable git svn
    precmd() {
        vcs_info
    }
    setopt prompt_subst

    if [[ -n "$SSH_CLIENT"  ||  -n "$SSH2_CLIENT" ]]; then
        context_color='green'
        p_host='%B%F{green}%M%f%b'
    else
        context_color='cyan'
        p_host='%F{yellow}%M%f'
    fi

    PS1=${(j::Q)${(Z:Cn:):-$'
        %F{${context_color}}[%f
        %(!.%K{red}%n%k.%F{red}%n%f)
        %F{${context_color}}@%f
        ${p_host}
        %F{${context_color}}\:%f
        %F{magenta}%~%f
        %F{${context_color}}]
        %(!.%K{red}%#%k.\$)
        %f
        " "
    '}}

    PS2=$'%F{${context_color}}%_ > %f'
    RPROMPT=$'%F{${context_color}}${vcs_info_msg_0_}%f'
}

setprompt

. ~/zsh/aliases.zshrc

PATH=/usr/local/opt/python/libexec/bin:$PATH
PATH=/usr/local/bin:/usr/local/sbin:$PATH
export PATH
